### ISSUE TITLE
Convolved flux ratio error reversed

### ISSUE THREAD

**Issue by ddobie** [ajstewart/racs-historical-transients#66]
For some sources (e.g. http://ada.physics.usyd.edu.au:8006/image/95/transients/view_source/119211/) the convolved flux is < 2x the SUMSS flux, but the non-convolved flux is > 2x the SUMSS flux. In this case the source is still interesting by our criteria (albeit quite weird), but the "convolved flux ratio error" message displays.

The error should be displayed, but this scenario is something to keep an eye out for if/when we throw away sources that have the error, as these sources should still be investigated.

**Comment by ddobie** [comment]
Another example: http://ada.physics.usyd.edu.au:8006/image/118/transients/view_source/156696/

**Comment by ajstewart** [comment]
I'm going to close this issue as the convolved flux error tag has been changed slightly for the next run, although it will still appear in this case. Also this is more of a user query method rather than an issue in the pipeline, I envision that maybe the crossmatches with the error will be checked at a later date.

I will also make a note in an expanded explanation doc of situations like this.
